### ISSUE TITLE
Improve validation reports to a better understanding

### ISSUE THREAD

**Issue by anitacaron** [hubmapconsortium/ccf-validation-tools#189]
Following today's meeting, here are some suggestions to improve the validation output.

A directory per table/report with

- [x] 1. A README.md explaining the report, high-level stats, and links to focused findings that the user can act on - _Partially done in PR #191_ 

- [x] 2. Individual markdown reports that give links to terms, frame the issues, etc, in markdown for ease of use - _Partially done in PR #191_ 

- [ ] 3. Potentially using [inline diagrams](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.blog%2F2022-02-14-include-diagrams-markdown-files-mermaid%2F&data=05%7C01%7Cellenmq%40iu.edu%7Cff6c171c5b6b4d37c85f08dac729dfa5%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C638041279919783329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zqzK%2BxM0UZsLT2EoNUMZG7eZaWcp08G%2F38kJQAtu%2BKU%3D&reserved=0) to show relationships and issues visually

- [X] 4. Potentially add row number references for users to quickly get back to the right spot in the sheet to edit - _Done in PR #191_ 

- [X] 5. Other files, including the rendered graph, maybe even the sheet at the time of validation (README should link back to the sheet for quick reference) - _Done in PR #208_ 

- [x] 6. Add commentary system to track changes in the ASCT+B tables - _Done in PR #205_ 
- [X] 7. Show reports in GH Pages - _Done in PR #197_ 
- [x] #218
- [X] 9. Tables should be extended to include deltaIC and sorted on this. - _Done in PR #207_
