### ISSUE TITLE
Create dashboard in validation reports page

### ISSUE THREAD

**Issue by anitacaron** [hubmapconsortium/ccf-validation-tools#247]
Use the reports for terms and relationships in the reports folder.
```[tasklist]
### Tasks
- [x] Remove indirect relation percentages
- [x] Add link to the reports for each table
- [x] Add colors. Green for percentage less than 50% and red for more than 50%
- [ ] Add description for each column
```
